name: bible_plus
version: 0.1.2
author: Stayman Hou <stayman.hou@gmail.com>
description: Library for reading PDB bible files.
homepage: https://github.com/StaymanHou/bible_plus_dart
environment:
  sdk: ">=1.23.0 <3.0.0"
dependencies:

dev_dependencies:
  test: ^1.5.1
